# HP CodeWay fixed header to load the pipeline templates
resources:
  repositories:
  - repository: templates
    type: githubenterprise
    name: codeway/templates
    endpoint: ghe
    # ref: refs/heads/some-branch # Set up a different branch for CodeWay templates. WARNING: It may be harmful  to use non-released pipelines.
 
# Define the triggers for your pipeline (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#triggers)
trigger: # Trigger on branches
- master
- "*"
# - release
# - develop
 
pr: # Trigger on pull requests towards branches
- master
# - develop
# - release
 
# Variable groups including configurations and secrets you want to use in this pipeline (Pipeline -> Library in ADO UI)
variables:
- group: Defaults
 
# HP CodeWay pipeline template to be executed and its parameters
stages:
- stage: build
  displayName: build
  jobs:
    - job: LintandTest
      displayName: LinandTest
      pool: CodeWayAWSLinux
      steps: 
        - checkout: self
          persistCredentials: true
        - template: steps/golang-lint-test-coverage-v1.yaml@templates
          parameters:
            gheUser: $(gh_user)
            gheToken: $(ghe_token)
            versionMajorMinor: 0.1
            linters: '--enable-all'
            golangVersion: "1.13.1"
            release: true 
        - script: |
            go build github.com/dexidp/dex/cmd/dex
          displayName: Go build
        - template: steps/golang-release-v1.yaml@templates
          parameters:
             githubToken: $(gh_token)
             gheUser: $(gh_user)
             golangVersion: "1.13.1"
             version: 0.1
        - template: steps/dockerBuildPushHarbor-v1.yaml@templates
          parameters:
            registry: 'harbor'
            project: 'wyplash'
            repo: 'dex'
            tags: |
              1.0.0 